package mediaedge

import "time"

// Baseline profile, Level 5.1: 4K at 30 fps exceeds the macroblock-rate
// limits of the previously advertised Level 3.1 contract.
const h264FMTP = "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e033"

const (
	h264RTPClockRate               = 90_000
	keyframeRequestMinimumInterval = 500 * time.Millisecond
	sourceControlRequestTimeout    = 2 * time.Second
	sourceSnapshotRequestTimeout   = 10 * time.Second
	sourceStallTimeout             = 2 * time.Second
	sourceRecoveryMinimumInterval  = time.Second
)

// SessionOffer is the non-trickle offer generated by the browser and sent
// directly to this Edge. Core and Agent do not participate in negotiation.
type SessionOffer struct {
	SDP string `json:"sdp"`
}

type SessionAnswer struct {
	SessionID        string            `json:"sessionId"`
	SDP              string            `json:"sdp"`
	DataChannelLabel string            `json:"dataChannelLabel"`
	Source           sourceDescription `json:"source"`
}

type sourceDescription struct {
	ID      string  `json:"id"`
	Width   int     `json:"width"`
	Height  int     `json:"height"`
	FPS     float64 `json:"fps"`
	FrameID string  `json:"frameId"`
	Codec   string  `json:"codec"`
}

// SourceStatus is intentionally metadata-only and never exposes RTP or a frame
// payload.
type SourceStatus struct {
	ID              string    `json:"id"`
	Active          bool      `json:"active"`
	Available       bool      `json:"available"`
	Online          bool      `json:"online"`
	Consumers       int       `json:"consumers"`
	Viewers         int       `json:"viewers"`
	RecordingID     string    `json:"recordingId,omitempty"`
	LastPacketAt    time.Time `json:"lastPacketAt,omitempty"`
	PacketsReceived uint64    `json:"packetsReceived"`
	BytesReceived   uint64    `json:"bytesReceived"`
	FramesInError   uint64    `json:"framesInError"`
	Width           int       `json:"width"`
	Height          int       `json:"height"`
	FPS             float64   `json:"fps"`
	FrameID         string    `json:"frameId"`
}
