package mediaedge

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/pion/interceptor"
	"github.com/pion/rtcp"
	"github.com/pion/rtp"
	"github.com/pion/webrtc/v4"
)

// Baseline profile, Level 5.1: 4K at 30 fps exceeds the macroblock-rate
// limits of the previously advertised Level 3.1 contract.
const h264FMTP = "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e033"

const (
	// The capture plugin paces RTP, but retain a generous socket buffer as a
	// defensive boundary for scheduler jitter and third-party sources. The kernel
	// may clamp this to its configured maximum; correctness never depends on it.
	rtpIngressReadBufferBytes = 4 << 20

	keyframeRequestMinimumInterval = 500 * time.Millisecond
	sourceControlRequestTimeout    = 2 * time.Second
	sourceSnapshotRequestTimeout   = 10 * time.Second
	sourceWatchInterval            = 250 * time.Millisecond
	sourceStallTimeout             = 2 * time.Second
	sourceRecoveryMinimumInterval  = time.Second
)

func h264CodecCapability() webrtc.RTPCodecCapability {
	return webrtc.RTPCodecCapability{
		MimeType: webrtc.MimeTypeH264, ClockRate: h264RTPClockRate, SDPFmtpLine: h264FMTP,
		RTCPFeedback: []webrtc.RTCPFeedback{
			{Type: webrtc.TypeRTCPFBCCM, Parameter: "fir"},
			{Type: webrtc.TypeRTCPFBNACK},
			{Type: webrtc.TypeRTCPFBNACK, Parameter: "pli"},
		},
	}
}

// Server is the target-local WebRTC fanout. A single RTP track per source is
// bound to every viewer, so multiple WebUI panels never create multiple source
// encoders or duplicate the capture workload.
type Server struct {
	config Config
	api    *webrtc.API

	mu         sync.RWMutex
	sources    map[string]*source
	sessions   map[string]*session
	closing    bool
	operations sync.WaitGroup

	lifecycleContext context.Context
	cancelLifecycle  context.CancelFunc

	listener   net.Listener
	httpServer *httpServer
	closeOnce  sync.Once
	closed     chan struct{}
}

type source struct {
	server *Server
	config SourceConfig
	track  *webrtc.TrackLocalStaticRTP

	lifecycleMu     sync.Mutex
	mu              sync.Mutex
	rtp             *net.UDPConn
	sessions        map[string]struct{}
	pending         int
	active          bool
	deactivateTimer *time.Timer
	deactivateEpoch uint64
	lastPacketAt    time.Time
	packetCount     uint64
	snapshots       map[string]Snapshot
	snapshotOrder   []string

	activeSince             time.Time
	lastKeyframeRequestAt   time.Time
	lastRecoveryAttemptAt   time.Time
	stallTimeout            time.Duration
	recoveryMinimumInterval time.Duration
	continuity              rtpContinuityRewriter
}

type session struct {
	id        string
	source    *source
	peer      *webrtc.PeerConnection
	closeOnce sync.Once
}

// SessionOffer is the non-trickle offer generated by the browser and sent
// directly to this Edge. Core and Agent do not participate in negotiation.
type SessionOffer struct {
	SDP string `json:"sdp"`
}

type SessionAnswer struct {
	SessionID        string            `json:"sessionId"`
	SDP              string            `json:"sdp"`
	DataChannelLabel string            `json:"dataChannelLabel"`
	Source           sourceDescription `json:"source"`
}

type sourceDescription struct {
	ID      string  `json:"id"`
	Width   int     `json:"width"`
	Height  int     `json:"height"`
	FPS     float64 `json:"fps"`
	FrameID string  `json:"frameId"`
	Codec   string  `json:"codec"`
}

// SourceStatus is intentionally metadata-only and never exposes RTP or a frame
// payload.
type SourceStatus struct {
	ID              string    `json:"id"`
	Active          bool      `json:"active"`
	Consumers       int       `json:"consumers"`
	LastPacketAt    time.Time `json:"lastPacketAt,omitempty"`
	PacketsReceived uint64    `json:"packetsReceived"`
	Width           int       `json:"width"`
	Height          int       `json:"height"`
	FPS             float64   `json:"fps"`
	FrameID         string    `json:"frameId"`
}

// New validates all network boundaries before creating a listener. In
// particular, ingest is never allowed from a LAN address: the capture plugin
// publishes to this gateway through the loopback interface only.
func New(config Config) (*Server, error) {
	normalized, err := config.normalized()
	if err != nil {
		return nil, err
	}
	lifecycleContext, cancelLifecycle := context.WithCancel(context.Background())
	mediaEngine := &webrtc.MediaEngine{}
	if err := mediaEngine.RegisterCodec(webrtc.RTPCodecParameters{
		RTPCodecCapability: h264CodecCapability(), PayloadType: 96,
	}, webrtc.RTPCodecTypeVideo); err != nil {
		cancelLifecycle()
		return nil, fmt.Errorf("register H264 media codec: %w", err)
	}
	registry := &interceptor.Registry{}
	if err := webrtc.RegisterDefaultInterceptors(mediaEngine, registry); err != nil {
		cancelLifecycle()
		return nil, fmt.Errorf("register WebRTC interceptors: %w", err)
	}
	settingEngine := webrtc.SettingEngine{}
	if len(normalized.PublicIPs) > 0 {
		settingEngine.SetNAT1To1IPs(append([]string(nil), normalized.PublicIPs...), webrtc.ICECandidateTypeHost)
	}
	server := &Server{
		config: normalized,
		api: webrtc.NewAPI(
			webrtc.WithMediaEngine(mediaEngine),
			webrtc.WithInterceptorRegistry(registry),
			webrtc.WithSettingEngine(settingEngine),
		),
		sources:          make(map[string]*source, len(normalized.Sources)),
		sessions:         make(map[string]*session),
		lifecycleContext: lifecycleContext,
		cancelLifecycle:  cancelLifecycle,
		closed:           make(chan struct{}),
	}
	for _, sourceConfig := range normalized.Sources {
		track, err := webrtc.NewTrackLocalStaticRTP(
			h264CodecCapability(),
			sourceConfig.ID,
			"xgc-media",
		)
		if err != nil {
			cancelLifecycle()
			return nil, fmt.Errorf("create media source %q track: %w", sourceConfig.ID, err)
		}
		server.sources[sourceConfig.ID] = &source{
			server: server, config: sourceConfig, track: track,
			sessions: make(map[string]struct{}), snapshots: make(map[string]Snapshot),
			stallTimeout: sourceStallTimeout, recoveryMinimumInterval: sourceRecoveryMinimumInterval,
		}
	}
	return server, nil
}

// Start validates every co-located source contract before opening any network
// listener. Source describe metadata is authoritative; optional configured
// metadata acts only as a strict deployment assertion.
func (server *Server) Start() error {
	sourceIDs := make([]string, 0, len(server.sources))
	for sourceID := range server.sources {
		sourceIDs = append(sourceIDs, sourceID)
	}
	sort.Strings(sourceIDs)
	for _, sourceID := range sourceIDs {
		source := server.sources[sourceID]
		described, err := describeSource(server.lifecycleContext, source.config)
		if err != nil {
			return fmt.Errorf("validate media source %q: %w", source.config.ID, err)
		}
		source.config = described
		source.continuity = newRTPContinuityRewriter(described.FPS)
	}
	for _, source := range server.sources {
		address, err := net.ResolveUDPAddr("udp", source.config.RTPListenAddress)
		if err != nil {
			server.Close()
			return fmt.Errorf("resolve source %q RTP listener: %w", source.config.ID, err)
		}
		connection, err := net.ListenUDP("udp", address)
		if err != nil {
			server.Close()
			return fmt.Errorf("listen for source %q RTP: %w", source.config.ID, err)
		}
		_ = connection.SetReadBuffer(rtpIngressReadBufferBytes)
		source.mu.Lock()
		source.rtp = connection
		source.mu.Unlock()
		go source.receiveRTP(connection)
		go source.watchForStall()
	}
	listener, err := net.Listen("tcp", server.config.ControlAddress)
	if err != nil {
		server.Close()
		return fmt.Errorf("listen for media edge control: %w", err)
	}
	server.listener = listener
	server.httpServer = newHTTPServer(server)
	go func() {
		if err := server.httpServer.serve(listener); err != nil && !errors.Is(err, net.ErrClosed) {
			// The process supervisor owns restart policy. A failed listener is
			// surfaced by readiness rather than silently re-binding here.
			_ = server.Close()
		}
	}()
	return nil
}

// ControlAddress returns the resolved HTTP listener address after Start.
func (server *Server) ControlAddress() string {
	if server == nil || server.listener == nil {
		return ""
	}
	return server.listener.Addr().String()
}

// RTPAddress returns the resolved local ingress endpoint for a source. It is
// primarily useful to launch a co-located capture plugin and for tests.
func (server *Server) RTPAddress(sourceID string) string {
	source := server.source(sourceID)
	if source == nil {
		return ""
	}
	source.mu.Lock()
	defer source.mu.Unlock()
	if source.rtp == nil {
		return ""
	}
	return source.rtp.LocalAddr().String()
}

func (server *Server) source(sourceID string) *source {
	server.mu.RLock()
	defer server.mu.RUnlock()
	return server.sources[sourceID]
}

func (server *Server) beginOperation(parent context.Context) (context.Context, func(), error) {
	server.mu.Lock()
	if server.closing {
		server.mu.Unlock()
		return nil, nil, errors.New("media edge is closing")
	}
	server.operations.Add(1)
	lifecycleContext := server.lifecycleContext
	server.mu.Unlock()

	operationContext, cancel := context.WithCancel(parent)
	stopLifecycleCancel := context.AfterFunc(lifecycleContext, cancel)
	finish := func() {
		_ = stopLifecycleCancel()
		cancel()
		server.operations.Done()
	}
	return operationContext, finish, nil
}

func (server *Server) isClosing() bool {
	server.mu.RLock()
	defer server.mu.RUnlock()
	return server.closing
}

func (server *Server) registerSession(item *session) error {
	server.mu.Lock()
	defer server.mu.Unlock()
	if server.closing {
		return errors.New("media edge is closing")
	}
	server.sessions[item.id] = item
	return nil
}

// OpenSession creates an answer after source activation succeeds. The source
// transition is reference counted; closing one panel cannot stop a feed still
// displayed in another panel.
func (server *Server) OpenSession(ctx context.Context, sourceID string, offer SessionOffer) (SessionAnswer, error) {
	if strings.TrimSpace(offer.SDP) == "" || len(offer.SDP) > 256<<10 {
		return SessionAnswer{}, errors.New("WebRTC offer SDP is required and must be at most 256 KiB")
	}
	operationContext, finishOperation, err := server.beginOperation(ctx)
	if err != nil {
		return SessionAnswer{}, err
	}
	defer finishOperation()

	source := server.source(sourceID)
	if source == nil {
		return SessionAnswer{}, fmt.Errorf("media source %q was not found", sourceID)
	}
	if err := source.acquire(operationContext); err != nil {
		return SessionAnswer{}, fmt.Errorf("activate media source %q: %w", sourceID, err)
	}
	pending := true
	defer func() {
		if pending {
			source.releasePending("")
		}
	}()

	peer, err := server.api.NewPeerConnection(webrtc.Configuration{ICEServers: append([]webrtc.ICEServer(nil), server.config.ICEServers...)})
	if err != nil {
		return SessionAnswer{}, fmt.Errorf("create WebRTC peer: %w", err)
	}
	closed := true
	defer func() {
		if closed {
			_ = peer.Close()
		}
	}()
	sessionID, err := newSnapshotID()
	if err != nil {
		return SessionAnswer{}, err
	}
	item := &session{id: sessionID, source: source, peer: peer}
	sender, err := peer.AddTrack(source.track)
	if err != nil {
		return SessionAnswer{}, fmt.Errorf("attach media track: %w", err)
	}
	go source.forwardKeyframeFeedback(sender)
	channel, err := peer.CreateDataChannel(ControlDataChannelLabel, nil)
	if err != nil {
		return SessionAnswer{}, fmt.Errorf("create media control data channel: %w", err)
	}
	server.installSnapshotControl(item, channel)
	if err := peer.SetRemoteDescription(webrtc.SessionDescription{Type: webrtc.SDPTypeOffer, SDP: offer.SDP}); err != nil {
		return SessionAnswer{}, fmt.Errorf("set WebRTC offer: %w", err)
	}
	answer, err := peer.CreateAnswer(nil)
	if err != nil {
		return SessionAnswer{}, fmt.Errorf("create WebRTC answer: %w", err)
	}
	gatherComplete := webrtc.GatheringCompletePromise(peer)
	if err := peer.SetLocalDescription(answer); err != nil {
		return SessionAnswer{}, fmt.Errorf("set WebRTC answer: %w", err)
	}
	if err := waitForGathering(operationContext, gatherComplete, server.config.SessionGatherTimeout); err != nil {
		return SessionAnswer{}, err
	}
	local := peer.LocalDescription()
	if local == nil || local.SDP == "" {
		return SessionAnswer{}, errors.New("WebRTC answer has no local SDP")
	}
	if err := server.registerSession(item); err != nil {
		return SessionAnswer{}, err
	}
	source.releasePending(item.id)
	pending = false
	closed = false

	handleConnectionState := func(state webrtc.PeerConnectionState) {
		switch state {
		case webrtc.PeerConnectionStateConnected:
			// Request the joining viewer's IDR only after its SRTP path is ready.
			// A request during SDP/ICE setup can be encoded and discarded before
			// this sender is bound, leaving the viewer black until the next GOP.
			source.requestKeyframeAsync(true)
		case webrtc.PeerConnectionStateFailed, webrtc.PeerConnectionStateClosed:
			server.closeSession(item)
		}
	}
	peer.OnConnectionStateChange(handleConnectionState)
	handleConnectionState(peer.ConnectionState())

	return SessionAnswer{
		SessionID: item.id, SDP: local.SDP, DataChannelLabel: ControlDataChannelLabel,
		Source: sourceDescription{ID: source.config.ID, Width: source.config.Width, Height: source.config.Height,
			FPS: source.config.FPS, FrameID: source.config.FrameID, Codec: "H264"},
	}, nil
}

func waitForGathering(ctx context.Context, completed <-chan struct{}, timeout time.Duration) error {
	timer := time.NewTimer(timeout)
	defer timer.Stop()
	select {
	case <-completed:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return errors.New("WebRTC ICE gathering timed out")
	}
}

// CloseSession is idempotent so an explicit panel unmount and an ICE failure
// can race without leaking a WebRTC peer or prematurely disabling a source.
func (server *Server) CloseSession(sessionID string) bool {
	server.mu.RLock()
	item := server.sessions[sessionID]
	server.mu.RUnlock()
	if item == nil {
		return false
	}
	server.closeSession(item)
	return true
}

func (server *Server) closeSession(item *session) {
	if item == nil {
		return
	}
	item.closeOnce.Do(func() {
		_ = item.peer.Close()
		item.source.removeSession(item.id)
		server.mu.Lock()
		delete(server.sessions, item.id)
		server.mu.Unlock()
	})
}

func (source *source) removeSession(sessionID string) {
	source.mu.Lock()
	delete(source.sessions, sessionID)
	empty := len(source.sessions) == 0 && source.pending == 0
	source.mu.Unlock()
	if empty {
		source.scheduleDeactivate()
	}
}

// acquire reserves one pending source consumer before activation. Pending
// consumers participate in the same reference count as established sessions,
// so a failed concurrent offer cannot deactivate a source while another offer
// is still gathering ICE candidates.
func (source *source) acquire(ctx context.Context) error {
	source.lifecycleMu.Lock()
	defer source.lifecycleMu.Unlock()
	if source.server.isClosing() {
		return errors.New("media edge is closing")
	}

	source.mu.Lock()
	source.pending++
	source.cancelDeactivateTimerLocked()
	if source.active {
		source.mu.Unlock()
		return nil
	}
	source.mu.Unlock()

	active := true
	if _, _, _, err := callSourceControl(ctx, source.config.ControlSocket, sourceControlRequest{Operation: "set-active", Active: &active}); err != nil {
		source.mu.Lock()
		source.pending--
		source.mu.Unlock()
		return err
	}
	source.mu.Lock()
	source.active = true
	source.activeSince = time.Now()
	source.lastRecoveryAttemptAt = time.Time{}
	source.mu.Unlock()
	return nil
}

// releasePending atomically converts a pending consumer into a live session,
// or releases it after a failed session/snapshot operation.
func (source *source) releasePending(sessionID string) {
	source.mu.Lock()
	if source.pending > 0 {
		source.pending--
	}
	if sessionID != "" {
		source.sessions[sessionID] = struct{}{}
	}
	unused := source.pending == 0 && len(source.sessions) == 0 && source.active
	source.mu.Unlock()
	if unused {
		source.scheduleDeactivate()
	}
}

func (source *source) cancelDeactivateTimerLocked() {
	source.deactivateEpoch++
	if source.deactivateTimer != nil {
		source.deactivateTimer.Stop()
		source.deactivateTimer = nil
	}
}

func (source *source) requestKeyframe(ctx context.Context) error {
	_, _, _, err := callSourceControl(ctx, source.config.ControlSocket, sourceControlRequest{Operation: "request-keyframe"})
	return err
}

// requestKeyframeAsync coalesces decoder feedback at the source boundary. A
// connection event is allowed to force one request because a keyframe emitted
// for an earlier viewer may already have passed before this viewer's SRTP path
// was ready. PLI/FIR requests share the source-wide rate limit.
func (source *source) requestKeyframeAsync(force bool) {
	now := time.Now()
	source.mu.Lock()
	if !source.active || (!force && !source.lastKeyframeRequestAt.IsZero() &&
		now.Sub(source.lastKeyframeRequestAt) < keyframeRequestMinimumInterval) {
		source.mu.Unlock()
		return
	}
	source.lastKeyframeRequestAt = now
	source.mu.Unlock()

	go func() {
		ctx, cancel := context.WithTimeout(source.server.lifecycleContext, sourceControlRequestTimeout)
		defer cancel()
		_ = source.requestKeyframe(ctx)
	}()
}

func (source *source) forwardKeyframeFeedback(sender *webrtc.RTPSender) {
	if sender == nil {
		return
	}
	buffer := make([]byte, 1500)
	for {
		count, _, err := sender.Read(buffer)
		if err != nil {
			return
		}
		packets, err := rtcp.Unmarshal(buffer[:count])
		if err != nil {
			continue
		}
		for _, packet := range packets {
			switch packet.(type) {
			case *rtcp.PictureLossIndication, *rtcp.FullIntraRequest:
				source.requestKeyframeAsync(false)
				// One control request satisfies every PLI/FIR in this compound
				// RTCP packet; do not let a browser amplify control traffic.
				goto nextPacket
			}
		}
	nextPacket:
	}
}

func (source *source) watchForStall() {
	ticker := time.NewTicker(sourceWatchInterval)
	defer ticker.Stop()
	for {
		select {
		case now := <-ticker.C:
			source.recoverIfStalled(now)
		case <-source.server.closed:
			return
		}
	}
}

func (source *source) recoverIfStalled(now time.Time) {
	source.lifecycleMu.Lock()
	defer source.lifecycleMu.Unlock()
	if source.server.isClosing() {
		return
	}

	source.mu.Lock()
	lastActivity := source.lastPacketAt
	if lastActivity.Before(source.activeSince) {
		lastActivity = source.activeSince
	}
	if !source.active || len(source.sessions) == 0 || lastActivity.IsZero() ||
		now.Sub(lastActivity) < source.stallTimeout ||
		(!source.lastRecoveryAttemptAt.IsZero() &&
			now.Sub(source.lastRecoveryAttemptAt) < source.recoveryMinimumInterval) {
		source.mu.Unlock()
		return
	}
	source.lastRecoveryAttemptAt = now
	source.mu.Unlock()

	ctx, cancel := context.WithTimeout(source.server.lifecycleContext, sourceControlRequestTimeout)
	defer cancel()
	active := true
	if _, _, _, err := callSourceControl(ctx, source.config.ControlSocket, sourceControlRequest{
		Operation: "set-active", Active: &active,
	}); err != nil {
		return
	}
	source.mu.Lock()
	source.lastKeyframeRequestAt = time.Now()
	source.mu.Unlock()
	_ = source.requestKeyframe(ctx)
}

func (source *source) scheduleDeactivate() {
	if source.server.isClosing() {
		return
	}
	source.mu.Lock()
	if !source.active || len(source.sessions) != 0 || source.pending != 0 {
		source.mu.Unlock()
		return
	}
	source.cancelDeactivateTimerLocked()
	epoch := source.deactivateEpoch
	grace := source.server.config.SessionGracePeriod
	source.deactivateTimer = time.AfterFunc(grace, func() {
		source.deactivateIfUnused(epoch)
	})
	source.mu.Unlock()
}

func (source *source) deactivateIfUnused(epoch uint64) {
	source.lifecycleMu.Lock()
	defer source.lifecycleMu.Unlock()
	if source.server.isClosing() {
		return
	}

	source.mu.Lock()
	if epoch != source.deactivateEpoch {
		source.mu.Unlock()
		return
	}
	source.deactivateTimer = nil
	if !source.active || len(source.sessions) != 0 || source.pending != 0 {
		source.mu.Unlock()
		return
	}
	// Commit the desired inactive state while holding the lifecycle gate. A new
	// consumer cannot observe stale active=true and skip its activation request
	// while this stop command is in flight.
	source.active = false
	source.activeSince = time.Time{}
	source.lastRecoveryAttemptAt = time.Time{}
	source.mu.Unlock()

	ctx, cancel := context.WithTimeout(source.server.lifecycleContext, sourceControlRequestTimeout)
	defer cancel()
	active := false
	_, _, _, _ = callSourceControl(ctx, source.config.ControlSocket, sourceControlRequest{Operation: "set-active", Active: &active})
}

func (source *source) receiveRTP(connection *net.UDPConn) {
	buffer := make([]byte, 2048)
	for {
		count, _, err := connection.ReadFromUDP(buffer)
		if err != nil {
			return
		}
		var packet rtp.Packet
		if err := packet.Unmarshal(buffer[:count]); err != nil {
			continue
		}
		if packet.PayloadType != 96 || len(packet.Payload) == 0 {
			continue
		}
		source.continuity.rewrite(&packet)
		now := time.Now()
		source.mu.Lock()
		source.packetCount++
		source.lastPacketAt = now
		source.mu.Unlock()
		if err := source.track.WriteRTP(&packet); err != nil && !errors.Is(err, io.ErrClosedPipe) {
			continue
		}
	}
}

// CaptureSnapshot obtains both display JPEG and exact RGB bytes from one
// source transaction. It is callable from a local calibration process and the
// WebRTC control channel; no preview polling or lossy video-frame extraction is
// involved.
func (server *Server) CaptureSnapshot(ctx context.Context, sourceID string) (Snapshot, error) {
	operationContext, finishOperation, err := server.beginOperation(ctx)
	if err != nil {
		return Snapshot{}, err
	}
	defer finishOperation()

	source := server.source(sourceID)
	if source == nil {
		return Snapshot{}, fmt.Errorf("media source %q was not found", sourceID)
	}
	if err := source.acquire(operationContext); err != nil {
		return Snapshot{}, fmt.Errorf("activate media source %q: %w", sourceID, err)
	}
	defer source.releasePending("")

	id, err := newSnapshotID()
	if err != nil {
		return Snapshot{}, err
	}
	response, jpeg, rgb, err := callSourceControl(operationContext, source.config.ControlSocket, sourceControlRequest{Operation: "snapshot", SnapshotID: id})
	if err != nil {
		return Snapshot{}, fmt.Errorf("capture source snapshot: %w", err)
	}
	if response.SnapshotID != "" && response.SnapshotID != id {
		return Snapshot{}, errors.New("capture source returned a mismatched snapshot ID")
	}
	if response.Width != source.config.Width || response.Height != source.config.Height ||
		response.RGBBytes != response.Width*response.Height*3 || response.PixelFormat != "rgb8" {
		return Snapshot{}, errors.New("capture source snapshot metadata does not match the media source")
	}
	if len(response.CameraMatrix) != 9 || len(response.Distortion) < 4 {
		return Snapshot{}, errors.New("capture source snapshot does not contain camera intrinsics")
	}
	snapshot := Snapshot{
		ID: id, SourceID: source.config.ID, FrameID: response.FrameID, TimestampNanoseconds: response.TimestampNanoseconds,
		Width: response.Width, Height: response.Height, PixelFormat: response.PixelFormat,
		JPEG: jpeg, RGB: rgb, CameraMatrix: append([]float64(nil), response.CameraMatrix...),
		Distortion: append([]float64(nil), response.Distortion...), ExpiresAt: time.Now().Add(server.config.SnapshotTTL),
	}
	if snapshot.FrameID == "" {
		snapshot.FrameID = source.config.FrameID
	}
	if snapshot.TimestampNanoseconds <= 0 {
		// A non-Gazebo source may have no source timestamp. Keep a monotonic
		// metadata value for that exceptional case without pretending this is a
		// Gazebo/ROS timestamp.
		snapshot.TimestampNanoseconds = time.Now().UnixNano()
	}
	source.storeSnapshot(snapshot)
	return snapshot, nil
}

func (source *source) storeSnapshot(snapshot Snapshot) {
	source.mu.Lock()
	defer source.mu.Unlock()
	now := time.Now()
	for id, current := range source.snapshots {
		if !current.ExpiresAt.After(now) {
			delete(source.snapshots, id)
		}
	}
	source.snapshots[snapshot.ID] = snapshot
	source.snapshotOrder = append(source.snapshotOrder, snapshot.ID)
	for len(source.snapshotOrder) > maximumSnapshots {
		oldest := source.snapshotOrder[0]
		source.snapshotOrder = source.snapshotOrder[1:]
		delete(source.snapshots, oldest)
	}
}

func (server *Server) Snapshot(snapshotID string) (Snapshot, bool) {
	server.mu.RLock()
	sources := make([]*source, 0, len(server.sources))
	for _, source := range server.sources {
		sources = append(sources, source)
	}
	server.mu.RUnlock()
	for _, source := range sources {
		source.mu.Lock()
		snapshot, found := source.snapshots[snapshotID]
		if found && !snapshot.ExpiresAt.After(time.Now()) {
			delete(source.snapshots, snapshotID)
			found = false
		}
		source.mu.Unlock()
		if found {
			return snapshot, true
		}
	}
	return Snapshot{}, false
}

// DeleteSnapshot releases an explicit calibration transaction immediately.
// It is deliberately separate from session teardown: a viewer may stay live
// while a calibration process consumes and discards a one-off RGB frame.
func (server *Server) DeleteSnapshot(snapshotID string) bool {
	server.mu.RLock()
	sources := make([]*source, 0, len(server.sources))
	for _, source := range server.sources {
		sources = append(sources, source)
	}
	server.mu.RUnlock()
	for _, source := range sources {
		source.mu.Lock()
		if _, found := source.snapshots[snapshotID]; !found {
			source.mu.Unlock()
			continue
		}
		delete(source.snapshots, snapshotID)
		for index, id := range source.snapshotOrder {
			if id == snapshotID {
				source.snapshotOrder = append(source.snapshotOrder[:index], source.snapshotOrder[index+1:]...)
				break
			}
		}
		source.mu.Unlock()
		return true
	}
	return false
}

func (server *Server) SourceStatuses() []SourceStatus {
	server.mu.RLock()
	sources := make([]*source, 0, len(server.sources))
	for _, source := range server.sources {
		sources = append(sources, source)
	}
	server.mu.RUnlock()
	statuses := make([]SourceStatus, 0, len(sources))
	for _, source := range sources {
		source.mu.Lock()
		statuses = append(statuses, SourceStatus{ID: source.config.ID, Active: source.active,
			Consumers: len(source.sessions), LastPacketAt: source.lastPacketAt.UTC(), PacketsReceived: source.packetCount,
			Width: source.config.Width, Height: source.config.Height, FPS: source.config.FPS, FrameID: source.config.FrameID})
		source.mu.Unlock()
	}
	sort.Slice(statuses, func(left, right int) bool { return statuses[left].ID < statuses[right].ID })
	return statuses
}

func (server *Server) installSnapshotControl(item *session, channel *webrtc.DataChannel) {
	var writeMu sync.Mutex
	channel.OnMessage(func(message webrtc.DataChannelMessage) {
		if !message.IsString {
			return
		}
		var request struct {
			Operation  string `json:"operation"`
			SnapshotID string `json:"snapshotId"`
		}
		if json.Unmarshal(message.Data, &request) != nil || request.Operation != "snapshot" {
			return
		}
		var snapshot Snapshot
		var err error
		if request.SnapshotID != "" {
			var found bool
			snapshot, found = server.Snapshot(request.SnapshotID)
			if !found || snapshot.SourceID != item.source.config.ID {
				err = errors.New("requested snapshot is unavailable")
			}
		} else {
			ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
			snapshot, err = server.CaptureSnapshot(ctx, item.source.config.ID)
			cancel()
		}
		writeMu.Lock()
		defer writeMu.Unlock()
		if err != nil {
			_ = channel.SendText(`{"operation":"snapshot","error":"snapshot unavailable"}`)
			return
		}
		metadata, _ := json.Marshal(struct {
			Operation string `json:"operation"`
			snapshotMetadata
		}{Operation: "snapshot", snapshotMetadata: snapshot.metadata()})
		if err := channel.SendText(string(metadata)); err != nil {
			return
		}
		_ = channel.Send(snapshot.JPEG)
	})
}

// Close stops the control listener, all WebRTC peers, and the local RTP
// sockets. It asks active capture sources to stop before returning.
func (server *Server) Close() error {
	if server == nil {
		return nil
	}
	var closeErr error
	server.closeOnce.Do(func() {
		server.mu.Lock()
		server.closing = true
		server.cancelLifecycle()
		server.mu.Unlock()
		close(server.closed)
		if server.httpServer != nil {
			closeErr = server.httpServer.close()
		}
		if server.listener != nil {
			if err := server.listener.Close(); err != nil && !errors.Is(err, net.ErrClosed) && closeErr == nil {
				closeErr = err
			}
		}
		// No operation can be added after closing was published under server.mu.
		// Cancellation bounds source-control I/O and ICE gathering, while this
		// wait prevents a late operation from publishing a session after the
		// teardown snapshot below.
		server.operations.Wait()

		server.mu.RLock()
		sessions := make([]*session, 0, len(server.sessions))
		for _, item := range server.sessions {
			sessions = append(sessions, item)
		}
		sources := make([]*source, 0, len(server.sources))
		for _, source := range server.sources {
			sources = append(sources, source)
		}
		server.mu.RUnlock()
		for _, item := range sessions {
			server.closeSession(item)
		}
		for _, source := range sources {
			source.lifecycleMu.Lock()
			source.mu.Lock()
			source.cancelDeactivateTimerLocked()
			connection := source.rtp
			source.rtp = nil
			source.active = false
			source.activeSince = time.Time{}
			source.lastRecoveryAttemptAt = time.Time{}
			source.mu.Unlock()
			if connection != nil {
				_ = connection.Close()
			}
			// Stop is idempotent and is deliberately unconditional: an activation
			// whose acknowledgement was lost may have enabled the physical source
			// without ever committing source.active=true locally.
			ctx, cancel := context.WithTimeout(context.Background(), sourceControlRequestTimeout)
			active := false
			if _, _, _, err := callSourceControl(ctx, source.config.ControlSocket, sourceControlRequest{Operation: "set-active", Active: &active}); err != nil && closeErr == nil {
				closeErr = fmt.Errorf("deactivate media source %q: %w", source.config.ID, err)
			}
			cancel()
			source.lifecycleMu.Unlock()
		}
	})
	return closeErr
}
